/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiLottieGeneratorRouteImport } from './routes/ai-lottie-generator'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as SvgToLottieRouteImport } from './routes/svg-to-lottie'
import { Route as DocsChar123SectionChar125RouteImport } from './routes/docs.{-$section}'
import { Route as ExamplesKeyRouteImport } from './routes/examples.$key'
import { Route as SIdRouteImport } from './routes/s.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLottieGeneratorRoute = AiLottieGeneratorRouteImport.update({
  id: '/ai-lottie-generator',
  path: '/ai-lottie-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const SvgToLottieRoute = SvgToLottieRouteImport.update({
  id: '/svg-to-lottie',
  path: '/svg-to-lottie',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123SectionChar125Route =
  DocsChar123SectionChar125RouteImport.update({
    id: '/docs/{-$section}',
    path: '/docs/{-$section}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesKeyRoute = ExamplesKeyRouteImport.update({
  id: '/examples/$key',
  path: '/examples/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-lottie-generator': typeof AiLottieGeneratorRoute
  '/community': typeof CommunityRoute
  '/svg-to-lottie': typeof SvgToLottieRoute
  '/docs/{-$section}': typeof DocsChar123SectionChar125Route
  '/examples/$key': typeof ExamplesKeyRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-lottie-generator': typeof AiLottieGeneratorRoute
  '/community': typeof CommunityRoute
  '/svg-to-lottie': typeof SvgToLottieRoute
  '/docs/{-$section}': typeof DocsChar123SectionChar125Route
  '/examples/$key': typeof ExamplesKeyRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-lottie-generator': typeof AiLottieGeneratorRoute
  '/community': typeof CommunityRoute
  '/svg-to-lottie': typeof SvgToLottieRoute
  '/docs/{-$section}': typeof DocsChar123SectionChar125Route
  '/examples/$key': typeof ExamplesKeyRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-lottie-generator'
    | '/community'
    | '/svg-to-lottie'
    | '/docs/{-$section}'
    | '/examples/$key'
    | '/s/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-lottie-generator'
    | '/community'
    | '/svg-to-lottie'
    | '/docs/{-$section}'
    | '/examples/$key'
    | '/s/$id'
  id:
    | '__root__'
    | '/'
    | '/ai-lottie-generator'
    | '/community'
    | '/svg-to-lottie'
    | '/docs/{-$section}'
    | '/examples/$key'
    | '/s/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiLottieGeneratorRoute: typeof AiLottieGeneratorRoute
  CommunityRoute: typeof CommunityRoute
  SvgToLottieRoute: typeof SvgToLottieRoute
  DocsChar123SectionChar125Route: typeof DocsChar123SectionChar125Route
  ExamplesKeyRoute: typeof ExamplesKeyRoute
  SIdRoute: typeof SIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-lottie-generator': {
      id: '/ai-lottie-generator'
      path: '/ai-lottie-generator'
      fullPath: '/ai-lottie-generator'
      preLoaderRoute: typeof AiLottieGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/svg-to-lottie': {
      id: '/svg-to-lottie'
      path: '/svg-to-lottie'
      fullPath: '/svg-to-lottie'
      preLoaderRoute: typeof SvgToLottieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{-$section}': {
      id: '/docs/{-$section}'
      path: '/docs/{-$section}'
      fullPath: '/docs/{-$section}'
      preLoaderRoute: typeof DocsChar123SectionChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/$key': {
      id: '/examples/$key'
      path: '/examples/$key'
      fullPath: '/examples/$key'
      preLoaderRoute: typeof ExamplesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiLottieGeneratorRoute: AiLottieGeneratorRoute,
  CommunityRoute: CommunityRoute,
  SvgToLottieRoute: SvgToLottieRoute,
  DocsChar123SectionChar125Route: DocsChar123SectionChar125Route,
  ExamplesKeyRoute: ExamplesKeyRoute,
  SIdRoute: SIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
