// Metro can't glob or import raw .css (see turkey.ts), so we inline the gallery
// as a TS module. Run `bun scripts/gen-examples.ts` after touching
// examples/popkorn/*.css to regenerate examples.gen.ts.
// ponytail: commit the generated file; a metro raw-text transformer would be
// more machinery than this one script warrants.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const dir = join(import.meta.dir, '../../../examples/popkorn');
const out = join(import.meta.dir, '../examples.gen.ts');

const files = readdirSync(dir).filter((f) => f.endsWith('.css')).sort();

const label = (name: string) =>
  name
    .replace(/\.css$/, '')
    .replace(/^\d+-/, '')
    .split('--')
    .map((p) => p.replace(/-/g, ' ').replace(/^\w/, (c) => c.toUpperCase()))
    .join(': ');

const entries = files.map((f) => {
  const source = readFileSync(join(dir, f), 'utf8');
  // Escape backslash and backtick for a template literal; ${ can't appear in the DSL.
  const escaped = source.replace(/\\/g, '\\\\').replace(/`/g, '\\`');
  return `  { key: ${JSON.stringify(f)}, label: ${JSON.stringify(label(f))}, source: \`${escaped}\` },`;
});

const banner = `// GENERATED by scripts/gen-examples.ts — do not edit by hand.\n// Source of truth: examples/popkorn/*.css.\n`;
writeFileSync(
  out,
  `${banner}export interface Example { key: string; label: string; source: string; }\n\nexport const examples: Example[] = [\n${entries.join('\n')}\n];\n`,
);

console.log(`Wrote ${files.length} examples to examples.gen.ts`);
