// GENERATED by scripts/gen-examples.ts — do not edit by hand.
// Source of truth: examples/popkorn/*.css.
export interface Example { key: string; label: string; source: string; }

export const examples: Example[] = [
  { key: "01-shapes.css", label: "Shapes", source: `/* Shapes — gradients, polystar, rounded rects, text, clip-path */
:root {
  width: 800px;
  height: 600px;
}

/* Gradient backdrop card with a gradient hairline border */
#card {
  type: rect;
  x: 90px;
  y: 120px;
  width: 620px;
  height: 380px;
  rx: 28px;
  ry: 28px;
  fill: linear-gradient(135deg, #1b1b3a 0%, #2d1b4e 100%);
  stroke: linear-gradient(90deg, #4ecdc4 0%, #f472b6 100%);
  stroke-width: 2px;
}

/* Radial-gradient orb */
#orb {
  type: circle;
  cx: 230px;
  cy: 310px;
  r: 82px;
  fill: radial-gradient(#ffe66d 0%, #ff6b6b 100%);
}

/* A five-point star (polystar geometry) with a gradient fill */
#star {
  type: star;
  sides: 5;
  outer-radius: 84px;
  inner-radius: 36px;
  cx: 410px;
  cy: 300px;
  fill: linear-gradient(180deg, #4ecdc4 0%, #60a5fa 100%);
  stroke: #ffffff;
  stroke-width: 2px;
}

/* Colour bands revealed through a circular clip-path */
#medallion {
  type: group;
  clip-path: circle(60 at 590 300);

  > #b1 { type: rect; x: 528px; y: 240px; width: 124px; height: 30px; fill: #4ecdc4; }
  > #b2 { type: rect; x: 528px; y: 270px; width: 124px; height: 30px; fill: #ffe66d; }
  > #b3 { type: rect; x: 528px; y: 300px; width: 124px; height: 30px; fill: #f472b6; }
  > #b4 { type: rect; x: 528px; y: 330px; width: 124px; height: 30px; fill: #60a5fa; }
}

/* Text takes a gradient fill just like a shape */
#title {
  type: text;
  content: "Popkorn";
  x: 400px;
  y: 195px;
  font-size: 52px;
  font-weight: bold;
  text-anchor: middle;
  fill: linear-gradient(90deg, #ffe66d 0%, #f472b6 100%);
}

#subtitle {
  type: text;
  content: "shapes · gradients · text · clip";
  x: 400px;
  y: 470px;
  font-size: 19px;
  text-anchor: middle;
  fill: #8b8ba7;
}
` },
  { key: "02-basics--bouncy-ball.css", label: "Basics: Bouncy ball", source: `/* Bounce — per-keyframe easing with squash & stretch */
:root {
  width: 800px;
  height: 600px;
  background: #1a1a2e;
}

/*
 * Two channels, like a real rig: position is one clean gravity arc with a
 * single reversal at the floor, and squash lives in its own animation that
 * stays round through the flight and pulses only at impact. The beziers are
 * the tangents AE artists use for gravity (accelerate down, decelerate up).
 */
@keyframes ballBounce {
  0%   { transform: translateY(0);     animation-timing-function: cubic-bezier(0.333, 0, 1, 1); }
  50%  { transform: translateY(280px); animation-timing-function: cubic-bezier(0, 0, 0.667, 1); }
  100% { transform: translateY(0); }
}

@keyframes ballSquash {
  0%, 45%   { transform: scaleX(1) scaleY(1); }
  50%       { transform: scaleX(1.3) scaleY(0.7); }
  55%, 100% { transform: scaleX(1) scaleY(1); }
}

@keyframes shadowPulse {
  0%   { transform: scaleX(0.5) scaleY(1); opacity: 0.2; animation-timing-function: cubic-bezier(0.333, 0, 1, 1); }
  50%  { transform: scaleX(1.4) scaleY(1); opacity: 0.5; animation-timing-function: cubic-bezier(0, 0, 0.667, 1); }
  100% { transform: scaleX(0.5) scaleY(1); opacity: 0.2; }
}

#ground { type: rect; x: 100px; y: 480px; width: 600px; height: 4px; rx: 2px; fill: #4a4a6a; }

#ballShadow {
  type: ellipse; cx: 400px; cy: 475px; rx: 50px; ry: 8px; fill: #000000;
  transform-origin: center;
  animation: shadowPulse 1.2s linear infinite;
}

#ball {
  type: circle; cx: 400px; cy: 150px; r: 40px; fill: #ff6b6b;
  transform-origin: center bottom;
  animation: ballBounce 1.2s linear infinite, ballSquash 1.2s linear infinite;
}

#ballHighlight {
  type: circle; cx: 385px; cy: 135px; r: 12px; fill: #ffaaaa;
  transform-origin: 400px 190px;
  animation: ballBounce 1.2s linear infinite;
}
` },
  { key: "03-basics--dominoes.css", label: "Basics: Dominoes", source: `/* Motion — a domino run. A ball rolls in at constant speed and topples a colour
   cascade; each tile falls under gravity (accelerating ease-in), rebounds, holds
   flat for a beat, then rises to reset. One composed phrase, staggered by delay
   so the wave reads as choreography — not a chart. */
:root {
  width: 800px;
  height: 600px;
}

/* Stand and wait, then fall fast (gravity), snap-rebound on impact, lie still (the
   held beat), and stand back up. The fall sits at 45% of the timeline so each tile
   waits upright until the ball reaches it. Every keyframe restates the transform so
   the rotate track never drops to base. */
@keyframes topple {
  0%   { transform: rotate(0deg);  animation-timing-function: linear; }
  45%  { transform: rotate(0deg);  animation-timing-function: cubic-bezier(0.5, 0, 0.85, 0.35); }
  58%  { transform: rotate(84deg); animation-timing-function: ease-out; }
  62%  { transform: rotate(79deg); animation-timing-function: ease-in-out; }
  82%  { transform: rotate(79deg); animation-timing-function: ease-in-out; }
  94%  { transform: rotate(0deg);  animation-timing-function: linear; }
  100% { transform: rotate(0deg); }
}

/* The ball crosses at a steady linear pace, spinning as it goes; it fades in at the
   left and out past the right so the loop seam is invisible. */
@keyframes roll {
  0%   { transform: translateX(161px)  rotate(0deg);    opacity: 0; }
  3%   { transform: translateX(190px)  rotate(76deg);   opacity: 1; }
  68%  { transform: translateX(825px)  rotate(1731deg); opacity: 1; }
  72%  { transform: translateX(864px)  rotate(1833deg); opacity: 0; }
  100% { transform: translateX(1137px) rotate(2546deg); opacity: 0; }
}

#shelf { type: rect; x: 140px; y: 440px; width: 540px; height: 8px; rx: 4px; fill: #23233f; }

/* A standing tile, pivoting about its base so it topples like a domino */
@define domino {
  type: rect; y: 344px; width: 20px; height: 96px; rx: 3px;
  transform-origin: center bottom;
}

/* The stagger is expressed as negative (phase-shifted) delays so it never extends
   the scene duration past 3.2s — every animation shares that period and the loop
   is seam-free. Each delay is its cascade time minus one full period. */
#d1 { use: domino; x: 200px; fill: linear-gradient(180deg, #4ecdc4 0%, #2f8f88 100%); animation: topple 3.2s linear infinite -1.28s; }
#d2 { use: domino; x: 255px; fill: linear-gradient(180deg, #60a5fa 0%, #3567b0 100%); animation: topple 3.2s linear infinite -1.10s; }
#d3 { use: domino; x: 310px; fill: linear-gradient(180deg, #818cf8 0%, #4c53b0 100%); animation: topple 3.2s linear infinite -0.92s; }
#d4 { use: domino; x: 365px; fill: linear-gradient(180deg, #a855f7 0%, #6b2fa8 100%); animation: topple 3.2s linear infinite -0.74s; }
#d5 { use: domino; x: 420px; fill: linear-gradient(180deg, #f472b6 0%, #a83f7c 100%); animation: topple 3.2s linear infinite -0.56s; }
#d6 { use: domino; x: 475px; fill: linear-gradient(180deg, #fb7185 0%, #b03f52 100%); animation: topple 3.2s linear infinite -0.38s; }
#d7 { use: domino; x: 530px; fill: linear-gradient(180deg, #ffa94d 0%, #c06e26 100%); animation: topple 3.2s linear infinite -0.20s; }
#d8 { use: domino; x: 585px; fill: linear-gradient(180deg, #ffe66d 0%, #bfa32f 100%); animation: topple 3.2s linear infinite -0.02s; }

/* Base translate carries the vertical rest position; roll's translateX overrides x each frame */
#ball {
  type: group;
  transform: translate(0px, 418px);
  animation: roll 3.2s linear infinite;

  > #ballBody { type: circle; cx: 0; cy: 0; r: 22px; fill: radial-gradient(#ffffff 0%, #ff8f5e 100%); }
  > #ballMark { type: circle; cx: 11px; cy: 0; r: 5px; fill: #c94f2a; }
}
` },
  { key: "04-hierarchy.css", label: "Hierarchy", source: `/* ============================================================
   HIERARCHY — a solar system, nested groups 4–6 deep.

   The lesson: every group contributes exactly ONE motion, and a
   child inherits ALL of its ancestors'. So the little satellite
   at the bottom rides five spinning frames at once — the sun's
   orbit, Earth's orbit, the Moon's orbit and its own — without a
   single coordinate of its own doing the work. Transform
   inheritance composes down the tree.

   TREE  (→ = the motion that group adds to everything inside it):

   #system                       static frame, centres the stage
    ├─ starfield / guide rings    static + twinkle decoration
    ├─ #sun                       → breathes (scale pulse)
    ├─ #mercuryOrbit              → revolves (fast)
    ├─ #earthOrbit          L1    → revolves
    │   └─ #earth           L2    positions Earth on the ring
    │       ├─ #earthBody   L3    → spins  (Earth's day)
    │       └─ #moonOrbit   L3    → revolves (Moon around Earth)
    │           └─ #moon    L4    positions the Moon
    │               ├─ #moonBody
    │               └─ #satOrbit L5 → revolves (satellite)
    │                   └─ #sat  L6  the deepest child
    ├─ #marsOrbit                 → revolves; body spins
    └─ #saturnOrbit         L1    → revolves
        └─ #saturnCarrier   L2    positions Saturn on the ring
            └─ #saturnUpright L3  → COUNTER-rotates the orbit away
                so the tilted ring stays level in screen space
                while the orbit still sweeps Saturn around.
   ============================================================ */

:root {
  width: 800px;
  height: 600px;
  background: #05060f;
}

/* One turn. Reused by every revolution AND every spin — the only
   difference between "orbits the sun" and "spins in place" is
   which group in the tree the animation is attached to. */
@keyframes orbit {
  0%   { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

/* The sun's slow breath — a symmetric 0%/100% keyframe loops clean. */
@keyframes sunPulse {
  0%, 100% { transform: scale(1); }
  50%      { transform: scale(1.06); }
}

/* Corona glow, pulsing a touch out of phase with the body. */
@keyframes glowPulse {
  0%, 100% { transform: scale(1);    opacity: 0.55; }
  50%      { transform: scale(1.12); opacity: 0.8;  }
}

/* A few background stars fade in and out. */
@keyframes twinkle {
  0%, 100% { opacity: 0.25; }
  50%      { opacity: 1;    }
}

/* ── #system — the root frame. Purely positional (moves the whole
      universe to canvas centre); every orbit below inherits it. ── */
#system {
  type: group;
  transform: translate(400px, 300px);

  /* Starfield — cheap depth: static dots at varied size/opacity,
     a couple wired to \`twinkle\`. Coords are relative to centre. */
  > #s1  { type: circle; cx: -350px; cy: -230px; r: 1.5px; fill: #ffffff; opacity: 0.7; }
  > #s2  { type: circle; cx: -280px; cy:  180px; r: 1px;   fill: #cdd6ff; opacity: 0.5; }
  > #s3  { type: circle; cx: -180px; cy: -120px; r: 1.2px; fill: #ffffff;
           animation: twinkle 3s ease-in-out infinite; }
  > #s4  { type: circle; cx:  330px; cy: -200px; r: 1.5px; fill: #fff2cc; opacity: 0.8; }
  > #s5  { type: circle; cx:  300px; cy:  120px; r: 1px;   fill: #ffffff; opacity: 0.45; }
  > #s6  { type: circle; cx:  210px; cy:  250px; r: 1.3px; fill: #cdd6ff;
           animation: twinkle 2.4s ease-in-out infinite; }
  > #s7  { type: circle; cx: -320px; cy:   40px; r: 1px;   fill: #ffffff; opacity: 0.5; }
  > #s8  { type: circle; cx:  120px; cy: -250px; r: 1.4px; fill: #fff2cc; opacity: 0.7; }
  > #s9  { type: circle; cx: -110px; cy:  230px; r: 1px;   fill: #ffffff;
           animation: twinkle 3.6s ease-in-out infinite; }
  > #s10 { type: circle; cx:  360px; cy:   10px; r: 1.2px; fill: #cdd6ff; opacity: 0.6; }
  > #s11 { type: circle; cx:   40px; cy:  270px; r: 1px;   fill: #ffffff; opacity: 0.5; }
  > #s12 { type: circle; cx: -250px; cy: -260px; r: 1.3px; fill: #fff2cc; opacity: 0.65; }

  /* Faint guide rings — one per orbit radius, so the nesting reads
     even when a planet is on the far side. Stroke only, no fill. */
  > #ringMercury { type: circle; cx: 0; cy: 0; r: 90px;  fill: none; stroke: #141b33; stroke-width: 1px; }
  > #ringEarth   { type: circle; cx: 0; cy: 0; r: 150px; fill: none; stroke: #141b33; stroke-width: 1px; }
  > #ringMars    { type: circle; cx: 0; cy: 0; r: 205px; fill: none; stroke: #141b33; stroke-width: 1px; }
  > #ringSaturn  { type: circle; cx: 0; cy: 0; r: 262px; fill: none; stroke: #141b33; stroke-width: 1px; }

  /* Corona — big soft radial faded to transparent (8-digit alpha),
     behind the sun. No filters; the gradient alpha IS the glow. */
  > #sunGlow {
    type: circle; cx: 0; cy: 0; r: 95px;
    fill: radial-gradient(#ffcf7a 0%, #ffcf7a00 70%);
    transform-origin: center;
    animation: glowPulse 4s ease-in-out infinite;
  }

  /* ── #sun (L1 motion: breathe) ──────────────────────────────── */
  > #sun {
    type: circle; cx: 0; cy: 0; r: 42px;
    fill: radial-gradient(#fff6d5 0%, #ffb02e 100%);
    transform-origin: center;
    animation: sunPulse 4s ease-in-out infinite;
  }

  /* ── Mercury — one group, one motion: a fast tight revolution.
        No moon, no spin; it's the speed contrast for the others. ── */
  > #mercuryOrbit {
    type: group;
    animation: orbit 5s linear infinite;
    > #mercury {
      type: circle; cx: 90px; cy: 0; r: 7px;
      fill: radial-gradient(#b8b0a8 0%, #6b6560 100%);
    }
  }

  /* ── Earth system — the deep branch. Read it top to bottom:
        each \`> \` step adds one more spinning frame of reference. ── */
  > #earthOrbit {                         /* L1 → revolves round the sun */
    type: group;
    animation: orbit 12s linear infinite;

    > #earth {                            /* L2 — carrier: just positions Earth */
      type: group;
      transform: translate(150px, 0);

      /* L3 → Earth's own spin. It's a GROUP so the continents turn
         with it while the moon (a sibling, below) is unaffected —
         that separation is the whole point: spin ≠ orbit. */
      > #earthBody {
        type: group;
        animation: orbit 6s linear infinite;

        > #ocean    { type: circle;  cx: 0; cy: 0; r: 15px;
                      fill: radial-gradient(#7fc4ff 0%, #1b5fa8 100%); }
        > #land1    { type: ellipse; cx: -5px; cy: -4px; rx: 6px; ry: 4px; fill: #3f9c5a; }
        > #land2    { type: ellipse; cx:  6px; cy:  5px; rx: 4px; ry: 5px; fill: #4caf6a; }
        > #land3    { type: ellipse; cx:  7px; cy: -6px; rx: 3px; ry: 2px; fill: #3f9c5a; }
      }

      /* L3 → the Moon's revolution. Sits at Earth's position
         (inherited) but NOT Earth's spin, so its orbit plane is
         steady while the planet turns underneath. */
      > #moonOrbit {
        type: group;
        animation: orbit 3.2s linear infinite;

        > #moon {                         /* L4 — carrier: positions the Moon */
          type: group;
          transform: translate(38px, 0);

          > #moonBody {
            type: circle; cx: 0; cy: 0; r: 6px;
            fill: radial-gradient(circle 8px at -2px -2px, #eef0f4 0%, #9aa0aa 100%);
          }

          /* L5 → a satellite revolving round the Moon... */
          > #satOrbit {
            type: group;
            animation: orbit 1.4s linear infinite;
            /* L6 — the deepest node in the scene. Its screen path is
               the sum of five inherited rotations + this one, yet it
               only ever declares a single 13px offset. */
            > #sat { type: circle; cx: 13px; cy: 0; r: 2.5px; fill: #d6f5ff; }
          }
        }
      }
    }
  }

  /* ── Mars — revolves, and its body spins to show a polar cap.
        Two levels: orbit group → spinning body group. ── */
  > #marsOrbit {
    type: group;
    animation: orbit 18s linear infinite;

    > #mars {
      type: group;
      transform: translate(205px, 0);
      animation: orbit 9s linear infinite;   /* Mars' day */

      > #marsBody { type: circle;  cx: 0; cy: 0; r: 11px;
                    fill: radial-gradient(#ff9e7d 0%, #b23a1e 100%); }
      > #marsCap  { type: ellipse; cx: 0; cy: -8px; rx: 4px; ry: 2.5px; fill: #ffe3d6; }
    }
  }

  /* ── Saturn — the COUNTER-ROTATION lesson. ────────────────────
        #saturnOrbit spins the whole subtree round the sun. Inside,
        #saturnUpright runs the SAME orbit in \`reverse\`, so the two
        rotations cancel (parent +θ, child −θ → net 0). Result:
        Saturn keeps a fixed screen orientation — the flat ring
        stays level as it's carried around, instead of tumbling.
        Position still orbits, because the translate lives ABOVE
        the counter-rotation, on #saturnCarrier. ── */
  > #saturnOrbit {                         /* L1 → revolves */
    type: group;
    animation: orbit 26s linear infinite;

    > #saturnCarrier {                     /* L2 — positions Saturn on the ring */
      type: group;
      transform: translate(262px, 0);

      > #saturnUpright {                   /* L3 → cancels the orbit's rotation */
        type: group;
        animation: orbit 26s linear infinite reverse;

        /* Ring behind the body (document order) — a stroked ellipse
           reads as a tilted disc; the body hides its front centre. */
        > #saturnRing {
          type: ellipse; cx: 0; cy: 0; rx: 34px; ry: 11px;
          fill: none; stroke: #e7cf9c; stroke-width: 4px; opacity: 0.85;
        }
        > #saturnBody {
          type: circle; cx: 0; cy: 0; r: 16px;
          fill: radial-gradient(#f5d9a0 0%, #c99a54 100%);
        }

        /* A small moon riding INSIDE the upright frame — its orbit
           plane is steady too, thanks to the counter-rotation. */
        > #titanOrbit {
          type: group;
          animation: orbit 4s linear infinite;
          > #titan { type: circle; cx: 30px; cy: 0; r: 4px;
                     fill: radial-gradient(#ffd9a0 0%, #c98a4a 100%); }
        }
      }
    }
  }
}
` },
  { key: "05-motion-path.css", label: "Motion path", source: `/* Motion path — travel a route by arc length; offset-rotate faces the tangent.
   The stadium circuit is centred on the 800×600 stage with generous margins. */
:root {
  width: 800px;
  height: 600px;
  background: #0b1021;
}

@keyframes fly {
  0%   { offset-distance: 0%;   }
  100% { offset-distance: 100%; }
}

/* The route itself, drawn once as a dashed guide (x 90..710, y 170..430) */
#route {
  type: path;
  d: "M 220 170 L 580 170 A 130 130 0 0 1 580 430 L 220 430 A 130 130 0 0 1 220 170 Z";
  fill: none;
  stroke: #2a3350;
  stroke-width: 3px;
  stroke-dasharray: 10px 12px;
  stroke-linecap: round;
}

/* A little paper plane, drawn nose-first along +x so the tangent aims it */
@define plane {
  type: path;
  d: "M -14 -9 L 16 0 L -14 9 L -6 0 Z";
  stroke: #0b1021;
  stroke-width: 1px;
  offset-path: path("M 220 170 L 580 170 A 130 130 0 0 1 580 430 L 220 430 A 130 130 0 0 1 220 170 Z");
  offset-rotate: auto;
}

/* Three planes on one loop, staggered by negative delay (already in flight) */
#plane1 { use: plane; fill: #ffe66d; animation: fly 6s linear infinite;      }
#plane2 { use: plane; fill: #4ecdc4; animation: fly 6s linear infinite -2s;  }
#plane3 { use: plane; fill: #f472b6; animation: fly 6s linear infinite -4s;  }
` },
  { key: "06-trim-path.css", label: "Trim path", source: `/* Trim path — a handwritten "Hello" inked on by an animated trim, like a pen writing.
   The word is one open path; trim-end sweeps 0→100% to reveal the stroke (the draw-on),
   then trim-start sweeps up to retract it — both ends finish at 100% (empty), matching
   the 0% state, so the loop closes on a blank canvas with no pop. */
:root {
  width: 800px;
  height: 600px;
  background: #0b0f1e;
}

/* Pen writing: reveal with trim-end, hold the finished word, then wipe with trim-start. */
@keyframes write {
  0%   { trim-start: 0%;   trim-end: 0%;   animation-timing-function: ease-out;    }
  50%  { trim-start: 0%;   trim-end: 100%;                                          } /* word fully written */
  62%  { trim-start: 0%;   trim-end: 100%; animation-timing-function: ease-in-out; } /* hold, then lift the pen */
  100% { trim-start: 100%; trim-end: 100%;                                          }
}

/* The ink breathes 9→10→9px — the animated stroke-width the source carried, thickest as
   the word completes. */
@keyframes ink {
  0%   { stroke-width: 9px;  }
  50%  { stroke-width: 10px; }
  100% { stroke-width: 9px;  }
}

#hello {
  type: path;
  /* One continuous handwritten stroke, centred on the origin (verbatim from the source glyph). */
  d: 'M -145.66 43.75 C -145.66 43.75 -86.11 10.26 -81.85 -26.16 C -79.42 -46.94 -98.57 -44.14 -101.43 -23.01 C -103.76 -5.76 -109.6 40.56 -109.6 40.56 C -109.6 40.56 -103.98 -0.03 -85.85 1.75 C -65.94 4.08 -91.98 40.05 -69 40.31 C -48.57 40.53 -27.64 22.69 -26.87 10.94 C -25.99 -2.6 -44.36 -4.89 -50.02 11.97 C -55.23 27.46 -43.58 44.9 -23.54 40.58 C 7.34 33.92 22.48 -10.83 23.94 -26.08 C 25.47 -42.16 13.72 -43.69 6.57 -29.4 C -0.1 -16.04 -11.24 37.09 12.96 41.58 C 41.81 46.94 64.28 -5.91 67.09 -23.78 C 69.8 -41.07 58.66 -45.95 50.23 -30.67 C 41.17 -14.22 27.84 44.08 59.94 41.33 C 86.75 39.03 76.92 2.26 102.9 -0.05 C 114.56 -1.09 119.39 9.92 118.53 21.03 C 117.64 32.65 106.66 42.47 95.81 40.94 C 85.9 39.54 80.84 25.97 83.43 17.07 C 86.62 6.09 96.66 0.12 102.9 -0.05 C 111.77 -0.29 116.23 5.33 124.15 5.2 C 131.18 5.09 138.27 -2.92 138.27 -2.92';
  fill: none;
  stroke: linear-gradient(90deg, #ff6b6b 0%, #ffd93d 50%, #4ecdc4 100%);
  stroke-width: 9px;
  stroke-linecap: round;
  stroke-linejoin: round;
  transform: translate(407px, 300px) scale(1.9);
  animation: write 5s infinite, ink 5s ease-in-out infinite;
}
` },
  { key: "07-morph.css", label: "Morph", source: `/* Morph — path 'd' interpolation with animated gradient stops.
   Both keyframes share the same command sequence (M C C C C Z) and stop count,
   so 'd' and 'fill' interpolate. Break either and it holds instead. */
:root {
  width: 800px;
  height: 600px;
  background: #0f0f1e;
}

@keyframes blob {
  0% {
    d: 'M 400 150 C 483 150 550 217 550 300 C 550 383 483 450 400 450 C 317 450 250 383 250 300 C 250 217 317 150 400 150 Z';
    fill: linear-gradient(45deg, #ff6b6b 0%, #4ecdc4 100%);
  }
  100% {
    d: 'M 400 130 C 520 180 580 240 560 320 C 540 400 460 470 380 460 C 300 450 230 380 250 290 C 270 200 300 90 400 130 Z';
    fill: linear-gradient(45deg, #ffe66d 0%, #a855f7 100%);
  }
}

#blob {
  type: path;
  d: 'M 400 150 C 483 150 550 217 550 300 C 550 383 483 450 400 450 C 317 450 250 383 250 300 C 250 217 317 150 400 150 Z';
  fill: linear-gradient(45deg, #ff6b6b 0%, #4ecdc4 100%);
  animation: blob 3s ease-in-out infinite alternate;
}
` },
  { key: "08-symbols.css", label: "Symbols", source: `/* Symbols — a starry night built from one reusable star.
   The pedagogical payload: @define a shape once, \`use:\` it many times, and
   override only what differs per instance (position, colour, size, twinkle
   timing) right at the use-site. The moon and hills are plain nodes framing it. */
:root {
  width: 800px;
  height: 600px;
  background: #0b1026;
}

@keyframes twinkle {
  0%, 100% { transform: scale(1);   opacity: 0.45; }
  50%      { transform: scale(1.5); opacity: 1;    }
}

/* The reusable symbol: a real 5-pointed star with a soft glow halo.
   Every declaration here is a default — any #use-site below can override it.
   \`transform-origin: center\` keeps the twinkle pulse scaling in place. */
@define star {
  type: star;
  sides: 5;
  outer-radius: 15px;
  inner-radius: 6px;
  fill: #eaf1ff;
  transform-origin: center;
  filter: drop-shadow(0 0 5px rgba(255, 255, 255, 0.4));
  animation: twinkle 2.4s ease-in-out infinite;
}

/* Crescent moon: a pale disc with a second disc masked out of it
   (\`alpha-invert\` = destination-out = subtract) to carve the crescent. The
   drop-shadow lives on the *group*, not the disc, so it glows the composited
   crescent — put it on the disc and the shadow is computed from the full
   circle's alpha (before the mask), ghosting a ring around the whole disc. */
#moon {
  filter: drop-shadow(0 0 14px rgba(246, 243, 216, 0.45));
  > #moon-disc {
    type: circle;
    cx: 660px; cy: 160px; r: 46px;
    fill: #f6f3d8;
    mask: #moon-shade alpha-invert;
  }
}
#moon-shade {
  type: circle;
  cx: 640px; cy: 144px; r: 44px;
  fill: #f6f3d8;
}

/* The starfield: twelve instances of the one symbol, sorted into three depth
   tiers to fake parallax. Each use-site overrides only what makes that star
   different, and the tier sets three channels together: NEAR stars are big,
   bright-white and twinkle slowly; FAR stars are tiny, dim blue-grey and
   twinkle fast. (Size/colour ride on the overrides, not \`scale\`/\`opacity\`, so
   they never fight the twinkle animation.) A negative \`animation-delay\`
   desyncs each into a shimmer instead of pulsing in lockstep. */
/* near — big, bright, slow */
#s1  { use: star; cx: 110px; cy: 200px; fill: #f8fafc; outer-radius: 19px; inner-radius: 9px; animation-delay: -0.2s; animation-duration: 3.4s; }
#s3  { use: star; cx: 200px; cy: 410px; fill: #f8fafc; outer-radius: 20px; inner-radius: 9px; animation-delay: -0.7s; animation-duration: 3.6s; }
#s9  { use: star; cx: 470px; cy: 430px; fill: #f8fafc; outer-radius: 18px; inner-radius: 8px; animation-delay: -1.0s; animation-duration: 3.3s; }
/* mid */
#s2  { use: star; cx: 250px; cy: 250px; fill: #cfe3ff; outer-radius: 12px; inner-radius: 5px; animation-delay: -1.3s; animation-duration: 2.5s; }
#s5  { use: star; cx: 410px; cy: 360px; fill: #e0e7ff; outer-radius: 13px; inner-radius: 6px; animation-delay: -0.5s; animation-duration: 2.6s; }
#s10 { use: star; cx: 580px; cy: 420px; fill: #cfe3ff; outer-radius: 13px; inner-radius: 6px; animation-delay: -0.3s; animation-duration: 2.5s; }
#s12 { use: star; cx: 150px; cy: 330px; fill: #e0e7ff; outer-radius: 12px; inner-radius: 5px; animation-delay: -0.8s; animation-duration: 2.6s; }
/* far — tiny, dim, fast */
#s4  { use: star; cx: 360px; cy: 200px; fill: #8793c4; outer-radius: 8px;  inner-radius: 3px; animation-delay: -2.0s; animation-duration: 1.8s; }
#s6  { use: star; cx: 540px; cy: 300px; fill: #8793c4; outer-radius: 9px;  inner-radius: 4px; animation-delay: -1.7s; animation-duration: 1.9s; }
#s7  { use: star; cx: 300px; cy: 150px; fill: #8793c4; outer-radius: 8px;  inner-radius: 3px; animation-delay: -0.9s; animation-duration: 1.7s; }
#s8  { use: star; cx: 700px; cy: 380px; fill: #8793c4; outer-radius: 9px;  inner-radius: 4px; animation-delay: -2.3s; animation-duration: 2.0s; }
#s11 { use: star; cx: 740px; cy: 300px; fill: #8793c4; outer-radius: 8px;  inner-radius: 3px; animation-delay: -1.5s; animation-duration: 1.8s; }

/* Hills silhouette along the bottom, darker than the sky for depth. */
#hills {
  type: path;
  d: "M0 490 Q 200 450 400 485 Q 600 515 800 478 L 800 600 L 0 600 Z";
  fill: #05060f;
}

#title {
  type: text;
  content: "Symbols: one @define, many stars";
  x: 400px;
  y: 90px;
  font-size: 24px;
  font-family: sans-serif;
  font-weight: bold;
  text-anchor: middle;
  fill: #e2e8f0;
}
` },
  { key: "09-mask.css", label: "Mask", source: `/* Mask — big text revealed through a sweeping bar (luminance mask) */
:root {
  width: 800px;
  height: 600px;
  background: #0b1021;
}

/* The mask source is a white bar that sweeps across. Driving a luminance mask,
   it is never drawn itself — only its brightness shows the content through. */
@keyframes sweep {
  0%   { transform: translateX(-700px); }
  100% { transform: translateX(700px);  }
}

#reveal {
  type: text;
  content: "POPKORN";
  x: 400px;
  y: 360px;
  font-size: 150px;
  font-weight: 700;
  text-anchor: middle;
  fill: #ffe66d;
  mask: #wipe luminance;
}

#wipe {
  type: rect;
  x: 100px;
  y: 180px;
  width: 240px;
  height: 260px;
  fill: linear-gradient(90deg, #000000 0%, #ffffff 50%, #000000 100%);
  animation: sweep 3s ease-in-out infinite alternate;
}
` },
  { key: "10-interactive--cursor.css", label: "Interactive: Cursor", source: `/* Interactive — Sprout, a mochi creature, and the firefly that chases your
   cursor. The firefly rides input(cursor.x/y) and flares when you hold the
   mouse down (input(cursor.isDown)); Sprout idles with layered keyframes
   (breathing + an added flutter) and springs when you poke it (:hover/:active
   tweened by transition). Move the light around, then give Sprout a poke. */
:root {
  width: 800px;
  height: 600px;
  background: #0a1622;
  --cursor-x: input(cursor.x);
  --cursor-y: input(cursor.y);
  --down: input(cursor.isDown);
}

/* ---- ambient life (runs before you ever touch the scene) ---- */

/* Main idle: a slow breath (squash/stretch) with a gentle rock */
@keyframes idle {
  0%, 100% { transform: translateY(0px)  scale(1, 1)       rotate(-1.6deg); }
  50%      { transform: translateY(-9px) scale(0.98, 1.05) rotate(1.6deg); }
}
/* A faster, smaller bob ADDED on top of the idle bob — layered motion */
@keyframes flutter {
  0%, 100% { translate: 0px 0px; }
  50%      { translate: 0px -4px; }
}
/* Eyes blink on their own quick cycle */
@keyframes blink {
  0%, 92%, 100% { scale: 1 1; }
  96%           { scale: 1 0.08; }
}
/* Firefly breathes its glow so it feels alive even parked in a corner */
@keyframes flicker {
  0%, 100% { opacity: 0.55; }
  50%      { opacity: 1; }
}

/* ---- backdrop ---- */
#sky {
  type: rect; x: 0; y: 0; width: 800px; height: 600px;
  fill: linear-gradient(#12314a 0%, #0a1622 70%, #071019 100%);
}
/* soft vignette to focus the middle */
#vignette {
  type: rect; x: 0; y: 0; width: 800px; height: 600px;
  fill: radial-gradient(circle 520px at 400px 300px, #00000000 45%, #050d16 100%);
}
/* contact shadow that keeps Sprout grounded */
#shadow {
  type: ellipse; cx: 400px; cy: 452px; rx: 118px; ry: 20px;
  fill: radial-gradient(#00000066 0%, #00000000 72%);
}

/* ---- Sprout ---- the body shape carries the hover/active reaction, and its
   face rides along as children (they have no pseudo-state, so they never steal
   the hit; a poke anywhere on the body springs the whole creature) */
#sprout {
  type: ellipse; cx: 400px; cy: 330px; rx: 108px; ry: 96px;
  fill: radial-gradient(circle 150px at 356px 272px, #b7f0dd 0%, #5cc6ac 58%, #348d78 100%);
  transform-origin: 50% 100%;
  animation: idle 3.8s ease-in-out infinite, flutter 0.95s ease-in-out infinite;
  animation-composition: replace, add;
  transition: transform 0.45s cubic-bezier(0.34, 1.56, 0.64, 1);
  &:hover  { transform: translateY(-10px) scale(1.06); }
  &:active { transform: scale(1.15, 0.8); }

  /* little sprout leaf on top */
  > #stem {
    type: path; d: "M 400 238 C 398 214 402 200 400 184";
    fill: none; stroke: #3f9d84; stroke-width: 6px; stroke-linecap: round;
  }
  > #leaf {
    type: ellipse; cx: 413px; cy: 184px; rx: 18px; ry: 11px;
    fill: #7fd8b0; transform: rotate(-28deg); transform-origin: 400px 184px;
  }

  /* tummy highlight */
  > #belly {
    type: ellipse; cx: 400px; cy: 356px; rx: 74px; ry: 60px;
    fill: #ddf8ee; opacity: 0.35;
  }

  /* eyes (blink) with glossy glints */
  > #eyeL {
    type: ellipse; cx: 366px; cy: 318px; rx: 15px; ry: 19px;
    fill: #203a44; transform-origin: 366px 318px;
    animation: blink 4.2s ease-in-out infinite;
  }
  > #eyeR {
    type: ellipse; cx: 434px; cy: 318px; rx: 15px; ry: 19px;
    fill: #203a44; transform-origin: 434px 318px;
    animation: blink 4.2s ease-in-out infinite;
  }
  > #glintL { type: circle; cx: 371px; cy: 311px; r: 5px; fill: #ffffff; }
  > #glintR { type: circle; cx: 439px; cy: 311px; r: 5px; fill: #ffffff; }

  /* rosy cheeks */
  > #cheekL { type: ellipse; cx: 344px; cy: 348px; rx: 13px; ry: 8px; fill: #ff96ab; opacity: 0.5; }
  > #cheekR { type: ellipse; cx: 456px; cy: 348px; rx: 13px; ry: 8px; fill: #ff96ab; opacity: 0.5; }

  /* smile */
  > #mouth {
    type: path; d: "M 386 344 Q 400 356 414 344";
    fill: none; stroke: #2c5059; stroke-width: 4px; stroke-linecap: round;
  }
}

/* ---- firefly ---- follows the cursor; the outer flare only shows while the
   mouse is held down (opacity bound to cursor.isDown) */
#fireflyGlow {
  type: circle; cx: var(--cursor-x); cy: var(--cursor-y); r: 46px;
  fill: radial-gradient(#ffd97a55 0%, #ffb70300 68%);
  animation: flicker 2.4s ease-in-out infinite;
}
#flare {
  type: circle; cx: var(--cursor-x); cy: var(--cursor-y); r: 132px;
  fill: radial-gradient(#ffe6a800 40%, #ffdc7aaa 56%, #ffcf4d00 72%);
  opacity: var(--down);
}
#firefly {
  type: circle; cx: var(--cursor-x); cy: var(--cursor-y); r: 9px;
  fill: radial-gradient(#ffffff 0%, #ffd166 55%, #ffab00 100%);
}
` },
  { key: "11-interactive--hover-buttons.css", label: "Interactive: Hover buttons", source: `/* A row of round icon buttons, the kind you'd find in a toolbar or a media
   dock. At rest they drift and breathe gently. Point at one and it responds
   like a real control: it swells under the cursor, its ring finishes
   drawing itself in (or its dashes march around the rim), and its color
   warms — one unified press-me gesture, not a list of separate tricks. */
:root {
  width: 800px;
  height: 400px;
  background: #0d0f1a;
}

@keyframes bob {
  0%, 100% { translate: 0px 0px; }
  50%      { translate: 0px -8px; }
}
@keyframes spin-slow {
  0%   { rotate: 0deg; }
  100% { rotate: 360deg; }
}

/* ---- solid button: a dashed rim marches around it and it swells warm on
   hover. Idle life comes from a gentle bob, which never touches the
   properties the hover state owns (r / fill / stroke / stroke-dashoffset). ---- */
#play {
  type: circle; cx: 130px; cy: 200px; r: 48px;
  fill: #1f6f6b;
  stroke: #2f9d97;
  stroke-width: 4px;
  stroke-dasharray: 10px 7px;
  animation: bob 2.6s ease-in-out infinite;
  transition: r 250ms ease, fill 250ms ease, stroke 250ms ease, stroke-dashoffset 350ms ease-out;
  &:hover {
    r: 60px;
    fill: #2dd4bf;
    stroke: #99f6e4;
    stroke-dashoffset: -68px;
  }
}

/* ---- ring button: idles as an unfinished spinner slowly turning in place;
   hovering completes the ring, swells it, and warms its color. The idle
   rotation never touches trim-end/r/stroke, so it keeps turning underneath
   the hover tween instead of freezing. ---- */
#like {
  type: circle; cx: 310px; cy: 200px; r: 46px;
  fill: none;
  stroke: #6d63c7;
  stroke-width: 5px;
  stroke-linecap: round;
  trim-end: 78%;
  transform-origin: center;
  animation: spin-slow 6s linear infinite;
  transition: r 250ms ease, stroke 250ms ease, trim-end 300ms ease-out;
  &:hover {
    r: 58px;
    stroke: #a78bfa;
    trim-end: 100%;
  }
}

#share {
  type: circle; cx: 490px; cy: 200px; r: 48px;
  fill: #7a2e34;
  stroke: #a8434b;
  stroke-width: 4px;
  stroke-dasharray: 9px 6px;
  animation: bob 2.6s ease-in-out infinite 0.3s;
  transition: r 250ms ease, fill 250ms ease, stroke 250ms ease, stroke-dashoffset 350ms ease-out;
  &:hover {
    r: 60px;
    fill: #f43f5e;
    stroke: #fda4af;
    stroke-dashoffset: -60px;
  }
}

#volume {
  type: circle; cx: 670px; cy: 200px; r: 46px;
  fill: none;
  stroke: #8a6d1f;
  stroke-width: 5px;
  stroke-linecap: round;
  trim-end: 65%;
  transform-origin: center;
  animation: spin-slow 6s linear infinite reverse;
  transition: r 250ms ease, stroke 250ms ease, trim-end 300ms ease-out;
  &:hover {
    r: 58px;
    stroke: #fbbf24;
    trim-end: 100%;
  }
}
` },
  { key: "12-state-machine--pip.css", label: "State machine: Pip", source: `/* State machine — Pip, a mascot with a mind of its own. Two @machines run
   concurrently and independently:

     @machine mood   pops in once (intro -> idle on complete), idles with a
                     breath loop, springs on every click (a bounce state whose
                     animation RESTARTS on each re-entry, back to idle on
                     complete), and dozes off after 6s of no attention
                     (a state-time timeout). Poke it to wake it.
     @machine blink  an unrelated eye-blink loop — winks, waits, winks again —
                     proving a second graph runs on its own clock.

   Click Pip. Then leave it alone and watch it get sleepy. */
:root {
  width: 800px;
  height: 600px;
  background: #0e0b1e;
}

/* ---- mood: the personality graph (initial state plays once, then loops) ---- */
@machine mood {
  initial: intro;
  state intro  { to: idle on complete; }         /* pop-in finished -> settle */
  state idle   {
    to: bounce on click(#pip);                    /* poked -> spring (first wins) */
    to: sleepy when style(state-time > 6s);       /* ignored for 6s -> doze off */
  }
  state bounce { to: idle on complete; }          /* spring finished -> settle */
  state sleepy { to: idle on click(#pip); }       /* poke wakes it back up */
}

/* ---- blink: a fully independent loop on its own clock ---- */
@machine blink {
  initial: watch;
  state watch { to: wink when style(state-time > 2800ms); }
  state wink  { to: watch on complete; }          /* wink plays once, then wait */
}

/* ---- state-driven animations (restart from the state's entry time) ---- */
@keyframes popIn {
  0%   { transform: scale(0);          }
  60%  { transform: scale(1.14);       animation-timing-function: ease-out; }
  80%  { transform: scale(0.94);       }
  100% { transform: scale(1);          }
}
@keyframes breathe {
  0%, 100% { transform: translateY(0)   scale(1, 1);       }
  50%      { transform: translateY(-7px) scale(0.98, 1.05); }
}
@keyframes bounce {
  0%   { transform: translateY(0)     scale(1, 1);      animation-timing-function: ease-out; }
  25%  { transform: translateY(-78px) scale(0.9, 1.14); animation-timing-function: ease-in;  }
  55%  { transform: translateY(0)     scale(1.16, 0.8); animation-timing-function: ease-out; }
  72%  { transform: translateY(-18px) scale(0.97, 1.05); animation-timing-function: ease-in;  }
  100% { transform: translateY(0)     scale(1, 1);      }
}
@keyframes snooze {
  0%, 100% { transform: rotate(-3.5deg) translateY(2px);  }
  50%      { transform: rotate(3.5deg)  translateY(-2px); }
}
@keyframes wink {
  0%, 100% { scale: 1 1;   }
  50%      { scale: 1 0.08; }
}
@keyframes floatZ {
  0%   { opacity: 0;    translate: 0px 0px;   }
  25%  { opacity: 0.95; }
  100% { opacity: 0;    translate: 20px -54px; }
}

/* ---- backdrop ---- */
#sky {
  type: rect; x: 0; y: 0; width: 800px; height: 600px;
  fill: linear-gradient(#1c1740 0%, #0e0b1e 68%, #08060f 100%);
}
#spot {
  type: ellipse; cx: 400px; cy: 300px; rx: 360px; ry: 300px;
  fill: radial-gradient(#3a2f7a55 0%, #3a2f7a00 70%);
}
#shadow {
  type: ellipse; cx: 400px; cy: 452px; rx: 110px; ry: 20px;
  fill: radial-gradient(#00000066 0%, #00000000 72%);
}

/* sleepy Z's — hidden (opacity 0) until the sleepy state animates them in */
#zzz {
  type: text; content: "z z z"; x: 486px; y: 246px;
  font-size: 30px; font-family: sans-serif; font-weight: bold;
  text-anchor: start; fill: #b9a7ff; opacity: 0;
  transform: rotate(-8deg); transform-origin: 486px 246px;
  &:state(mood.sleepy) { animation: floatZ 2.6s ease-out infinite; }
}

/* ---- Pip ---- the whole creature is the click target (click(#pip)); the mood
   machine drives the group transform, so every state animation moves the body
   and face together, anchored at Pip's feet ---- */
#pip {
  type: group;
  transform-origin: 400px 410px;
  &:state(intro)  { animation: popIn  700ms ease-out; }
  &:state(idle)   { animation: breathe 3.4s ease-in-out infinite; }
  &:state(bounce) { animation: bounce 720ms ease-in-out; }
  &:state(sleepy) { animation: snooze 3s   ease-in-out infinite; }

  /* antenna bobble */
  > #stalk {
    type: path; d: "M 400 262 C 398 240 404 228 400 214";
    fill: none; stroke: #7b6cd6; stroke-width: 6px; stroke-linecap: round;
  }
  > #bobble { type: circle; cx: 400px; cy: 208px; r: 11px; fill: #ffd166; }
  > #bobbleGlow { type: circle; cx: 400px; cy: 208px; r: 20px;
    fill: radial-gradient(#ffd16688 0%, #ffd16600 70%); }

  /* body */
  > #body {
    type: ellipse; cx: 400px; cy: 336px; rx: 96px; ry: 90px;
    fill: radial-gradient(circle 150px at 356px 280px, #d9c9ff 0%, #9b7ff0 56%, #6a4fc4 100%);
  }
  > #belly { type: ellipse; cx: 400px; cy: 362px; rx: 66px; ry: 54px;
    fill: #efe6ff; opacity: 0.32; }

  /* cheeks */
  > #cheekL { type: ellipse; cx: 342px; cy: 354px; rx: 13px; ry: 8px; fill: #ff8fb8; opacity: 0.55; }
  > #cheekR { type: ellipse; cx: 458px; cy: 354px; rx: 13px; ry: 8px; fill: #ff8fb8; opacity: 0.55; }

  /* eyes — their own group so the blink machine can wink them as one unit */
  > #eyes {
    type: group; transform-origin: 400px 322px;
    &:state(blink.wink) { animation: wink 200ms ease-in-out; }
    > #eyeL   { type: ellipse; cx: 368px; cy: 322px; rx: 15px; ry: 19px; fill: #241a3d; }
    > #eyeR   { type: ellipse; cx: 432px; cy: 322px; rx: 15px; ry: 19px; fill: #241a3d; }
    > #glintL { type: circle;  cx: 373px; cy: 315px; r: 5px; fill: #ffffff; }
    > #glintR { type: circle;  cx: 437px; cy: 315px; r: 5px; fill: #ffffff; }
  }

  /* smile */
  > #mouth {
    type: path; d: "M 384 350 Q 400 364 416 350";
    fill: none; stroke: #3a2c5a; stroke-width: 4px; stroke-linecap: round;
  }
}

/* hint */
#hint {
  type: text; content: "click Pip  ·  or leave it be"; x: 400px; y: 528px;
  font-size: 17px; font-family: sans-serif; text-anchor: middle;
  fill: #6b6296;
}
` },
  { key: "13-state-machine--lamp.css", label: "State machine: Lamp", source: `/* Toggle — an incandescent bulb wired to a two-state @machine. Click the glass
   to flip it; each state has its own look AND its own motion:

     off  cold frosted glass, a grey filament, a metal screw base
     on   a warm glow stack — halo, spinning rays, hot glass, white-hot
          filament — plus a warm room wash and a brass-warmed base

   The whole recipe is the canonical toggle from the spec — two states, each
   pointing at the other \`on click(#bulb)\` — with :state() rules supplying the
   distinct styling and entry-anchored glow animations for each.

   The bulb is drawn in an unscaled ~200x260 "recipe" space inside #lamp, which
   translates + scales it to the centre of the 800x600 stage; every glass/base
   coordinate below is in that local recipe space (globe centre 100,98). */
:root {
  width: 800px;
  height: 600px;
  background: #171d2a;
}

@machine lamp {
  initial: off;
  state off { to: on  on click(#bulb); }
  state on  { to: off on click(#bulb); }
}

/* ---- glow choreography (restarts each time the bulb is switched on) ----
   fade-in and loop are split onto DISJOINT channels so they never fight:
   glowIn owns opacity, haloBreathe owns scale, raySpin owns rotate. */
@keyframes glowIn {
  0%   { opacity: 0; animation-timing-function: ease-out; }
  100% { opacity: 1; }
}
@keyframes haloBreathe {
  0%, 100% { transform: scale(1);    }
  50%      { transform: scale(1.09); }
}
@keyframes raysIn {
  0%   { opacity: 0; transform: scale(0.7); animation-timing-function: ease-out; }
  100% { opacity: 1; transform: scale(1);   }
}
@keyframes raySpin {
  0%   { transform: rotate(0deg);   }
  100% { transform: rotate(360deg); }
}
@keyframes roomOn {
  0%   { opacity: 0;    animation-timing-function: ease-out; }
  100% { opacity: 0.55; }
}

/* ---- room ---- warm wash that only exists while the lamp is on ---- */
#room {
  type: rect; x: 0; y: 0; width: 800px; height: 600px;
  fill: radial-gradient(circle 430px at 400px 232px, #ffce8a 0%, #ffce8a00 72%);
  opacity: 0;
  &:state(lamp.on) { animation: roomOn 800ms ease-out; }
}

/* ---- cord ---- the flex the bulb hangs from (stage coords) ---- */
#cord   { type: rect; x: 397px; y: 0px;   width: 6px; height: 118px; fill: #262b3d; }
#canopy { type: rect; x: 388px; y: 112px; width: 24px; height: 12px; rx: 4px; fill: #2f3550; }

/* ---- the bulb assembly, authored in local recipe space, scaled to centre ---- */
#lamp {
  type: group;
  transform: translate(210px, 44px) scale(1.9);

  /* 1. outer halo — soft bloom behind the glass, breathes while lit ---- */
  > #outerHalo {
    type: circle; cx: 100px; cy: 98px; r: 110px;
    fill: radial-gradient(circle 110px at 100px 98px, #ffdf8ed9 0%, #ffce6659 45%, #ffc14d00 100%);
    transform-origin: center; opacity: 0;
    &:state(lamp.on) { animation: glowIn 650ms ease-out, haloBreathe 3.2s ease-in-out infinite; }
  }

  /* 2. rays — a spoke burst that fades/spins in, never below the base ---- */
  > #rays {
    type: group; transform-origin: 100px 98px; opacity: 0;
    &:state(lamp.on) { animation: raysIn 550ms ease-out, raySpin 24s linear infinite; }
    > #ry1 { type: path; d: 'M 100 6 L 100 -16'; stroke: #ffd873; stroke-width: 6px; stroke-linecap: round; transform-origin: 100px 98px; }
    > #ry2 { type: path; d: 'M 100 6 L 100 -16'; stroke: #ffd873; stroke-width: 6px; stroke-linecap: round; transform-origin: 100px 98px; transform: rotate(45deg);   }
    > #ry3 { type: path; d: 'M 100 6 L 100 -16'; stroke: #ffd873; stroke-width: 6px; stroke-linecap: round; transform-origin: 100px 98px; transform: rotate(-45deg);  }
    > #ry4 { type: path; d: 'M 100 6 L 100 -16'; stroke: #ffd873; stroke-width: 6px; stroke-linecap: round; transform-origin: 100px 98px; transform: rotate(80deg);   }
    > #ry5 { type: path; d: 'M 100 6 L 100 -16'; stroke: #ffd873; stroke-width: 6px; stroke-linecap: round; transform-origin: 100px 98px; transform: rotate(-80deg);  }
    > #ry6 { type: path; d: 'M 100 6 L 100 -16'; stroke: #ffd873; stroke-width: 6px; stroke-linecap: round; transform-origin: 100px 98px; transform: rotate(135deg);  }
    > #ry7 { type: path; d: 'M 100 6 L 100 -16'; stroke: #ffd873; stroke-width: 6px; stroke-linecap: round; transform-origin: 100px 98px; transform: rotate(-135deg); }
  }

  /* 3. inner glow — the bright core inside the glass ---- */
  > #innerGlow {
    type: circle; cx: 100px; cy: 98px; r: 77px;
    fill: radial-gradient(circle 77px at 100px 98px, #fff7d6e6 0%, #ffe9a873 70%, #ffe9a800 100%);
    opacity: 0;
    &:state(lamp.on) { animation: glowIn 720ms ease-out; }
  }

  /* ---- screw base ---- metal off, brass-warmed on (fill swaps per state) ---- */
  > #collar {
    type: rect; x: 80px; y: 186px; width: 40px; height: 9px; rx: 3px; fill: #6e7684;
    &:state(lamp.on) { fill: #7d6f52; }
  }
  > #thread1 {
    type: rect; x: 76px; y: 197px; width: 48px; height: 9px; rx: 4.5px; transform-origin: center; transform: rotate(-4deg);
    fill: linear-gradient(90deg, #8d97a5 0%, #c6cdd8 50%, #7f8896 100%);
    &:state(lamp.on) { fill: linear-gradient(90deg, #a08a63 0%, #e8d9ae 50%, #93794f 100%); }
  }
  > #thread2 {
    type: rect; x: 76px; y: 208px; width: 48px; height: 9px; rx: 4.5px; transform-origin: center; transform: rotate(-6.5deg);
    fill: linear-gradient(90deg, #8d97a5 0%, #c6cdd8 50%, #7f8896 100%);
    &:state(lamp.on) { fill: linear-gradient(90deg, #a08a63 0%, #e8d9ae 50%, #93794f 100%); }
  }
  > #thread3 {
    type: rect; x: 76px; y: 219px; width: 48px; height: 9px; rx: 4.5px; transform-origin: center; transform: rotate(-9deg);
    fill: linear-gradient(90deg, #8d97a5 0%, #c6cdd8 50%, #7f8896 100%);
    &:state(lamp.on) { fill: linear-gradient(90deg, #a08a63 0%, #e8d9ae 50%, #93794f 100%); }
  }
  > #taper {
    type: path; d: 'M 82 228 L 118 228 L 110 240 L 90 240 Z'; fill: #6e7684;
    &:state(lamp.on) { fill: #7d6f52; }
  }
  > #tip {
    type: ellipse; cx: 100px; cy: 243px; rx: 9px; ry: 6px; fill: #4d5563;
    &:state(lamp.on) { fill: #5c5138; }
  }

  /* ---- glass silhouette ---- THE click target: click(#bulb) toggles the
     machine. Cold frosted gradient always; #hotGlass fades over it when on. */
  > #bulb {
    type: path;
    d: 'M 100 40 C 66 40 45 66 45 98 C 45 122 57 138 68 152 C 76 162 81 172 82 186 L 118 186 C 119 172 124 162 132 152 C 143 138 155 122 155 98 C 155 66 134 40 100 40 Z';
    fill: linear-gradient(135deg, #eef2f7 0%, #d7dee8 55%, #b9c4d4 100%);
    opacity: 0.9;
  }

  /* hot glass — same silhouette, lit radial; fades in over the cold glass ---- */
  > #hotGlass {
    type: path;
    d: 'M 100 40 C 66 40 45 66 45 98 C 45 122 57 138 68 152 C 76 162 81 172 82 186 L 118 186 C 119 172 124 162 132 152 C 143 138 155 122 155 98 C 155 66 134 40 100 40 Z';
    fill: radial-gradient(circle 86px at 100px 100px, #fffdf2 0%, #fff3c4 35%, #ffd873 70%, #ffb64a 100%);
    opacity: 0; pointer-events: none;
    &:state(lamp.on) { animation: glowIn 700ms ease-out; }
  }

  /* ---- filament ---- grey when off, white-hot when on; a bloom underlay
     brightens the whole squiggle while lit ---- */
  > #filamentGlow {
    type: path; d: 'M 84 148 C 84 128 92 128 92 144 C 92 128 100 128 100 144 C 100 128 108 128 108 144 C 108 128 116 128 116 148';
    fill: none; stroke: #ff9d2e; stroke-width: 7px; stroke-linecap: round; stroke-linejoin: round;
    opacity: 0; pointer-events: none;
    &:state(lamp.on) { animation: glowIn 700ms ease-out; }
  }
  > #supports {
    type: path; d: 'M 91 184 V 148 M 109 184 V 148';
    fill: none; stroke: #8a94a6; stroke-width: 3.5px; stroke-linecap: round;
    &:state(lamp.on) { stroke: #fff7d6; }
  }
  > #filament {
    type: path; d: 'M 84 148 C 84 128 92 128 92 144 C 92 128 100 128 100 144 C 100 128 108 128 108 144 C 108 128 116 128 116 148';
    fill: none; stroke: #8a94a6; stroke-width: 3.5px; stroke-linecap: round; stroke-linejoin: round;
    &:state(lamp.on) { stroke: #fff7d6; }
  }

  /* specular crescent — the glass reads as glass in both states ---- */
  > #specular {
    type: path; d: 'M 66 70 C 74 56 88 50 99 49 C 88 56 80 64 74 76 C 70 84 68 92 68 100 C 62 92 62 79 66 70 Z';
    fill: #ffffff; opacity: 0.72; pointer-events: none;
    &:state(lamp.on) { opacity: 0.85; }
  }
}

#hint {
  type: text; content: "click the bulb"; x: 400px; y: 565px;
  font-size: 17px; font-family: sans-serif; text-anchor: middle; fill: #5c607a;
}
` },
];
